export { useAdaptiveLogo } from './useAdaptiveLogo'
export { useErrorHandler } from './useErrorHandler'
export { useIntersectionObserver } from './useIntersectionObserver'
export { useOptimizedScrollDetection } from './useOptimizedScrollDetection'
export { usePerformanceMonitor } from './usePerformanceMonitor'
export { useScrollAnimation } from './useScrollAnimation'
export { useSectionObserver } from './useSectionObserver'
export { useTheme } from './useTheme'
export { useReducedMotion } from './useReducedMotion'
export { useThrottledScroll, useOptimizedScrollDetection as useOptimizedScrollDetectionHook } from './useThrottledScroll'